/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package codigo;

import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author pilar
 */
public class Form extends javax.swing.JFrame {

   DefaultTableModel tablaModel;
    String cadenaResult = "";
    GestorConexion   gc = new GestorConexion();
    public Form() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        DuracionCancion = new javax.swing.JTextField();
        LetrasCancion = new javax.swing.JTextField();
        AlbumCancion = new javax.swing.JTextField();
        InsertarAlbum = new javax.swing.JButton();
        ConsultaAlbum = new javax.swing.JButton();
        Id = new javax.swing.JTextField();
        TablaCancion = new javax.swing.JButton();
        TablaAlbum = new javax.swing.JButton();
        Titulo = new javax.swing.JTextField();
        Year = new javax.swing.JTextField();
        IdAlbumCon = new javax.swing.JTextField();
        InsertarCancion = new javax.swing.JButton();
        Caratula = new javax.swing.JTextField();
        TituloCancion = new javax.swing.JTextField();
        InsertCaratula = new javax.swing.JButton();
        Error = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        DuracionCancion.setText("Duracion");

        LetrasCancion.setText("Letras");

        AlbumCancion.setText("Album");

        InsertarAlbum.setText("Insertar album");
        InsertarAlbum.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                InsertarAlbumMouseClicked(evt);
            }
        });

        ConsultaAlbum.setText("Consulta id Album");
        ConsultaAlbum.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ConsultaAlbumMouseClicked(evt);
            }
        });

        Id.setText("ID album");

        TablaCancion.setText("Consulta tabla Cancion");
        TablaCancion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaCancionMouseClicked(evt);
            }
        });

        TablaAlbum.setText("Consulta tabla Album");
        TablaAlbum.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaAlbumMouseClicked(evt);
            }
        });

        Titulo.setText("Titulo");

        Year.setText("Year");

        IdAlbumCon.setText("1");

        InsertarCancion.setText("Insertar cancion");
        InsertarCancion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                InsertarCancionMouseClicked(evt);
            }
        });

        Caratula.setText("Caratula");
        Caratula.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CaratulaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CaratulaMouseEntered(evt);
            }
        });

        TituloCancion.setText("Titulo");
        TituloCancion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TituloCancionActionPerformed(evt);
            }
        });

        InsertCaratula.setText("Insertar Caratula");
        InsertCaratula.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                InsertCaratulaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(InsertarAlbum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(InsertarCancion))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(TituloCancion, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(Id, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(ConsultaAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(IdAlbumCon, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Caratula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(InsertCaratula))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(DuracionCancion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Year, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(LetrasCancion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(AlbumCancion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(TablaCancion)
                                .addGap(18, 18, 18)
                                .addComponent(TablaAlbum))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(Error, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InsertarAlbum)
                    .addComponent(Id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InsertarCancion)
                    .addComponent(TituloCancion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DuracionCancion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LetrasCancion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AlbumCancion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ConsultaAlbum)
                        .addComponent(IdAlbumCon, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Caratula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(InsertCaratula))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TablaCancion)
                    .addComponent(TablaAlbum))
                .addGap(168, 168, 168)
                .addComponent(Error)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void InsertarAlbumMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InsertarAlbumMouseClicked
        gc.insertarAlbum(Id.getText(), Titulo.getText(), Year.getText());
        TablaAlbumMouseClicked(evt);
        Error.setText(gc.cadenaResult);
    }//GEN-LAST:event_InsertarAlbumMouseClicked

    private void ConsultaAlbumMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ConsultaAlbumMouseClicked
        try {
            gc.conn1.setAutoCommit(false);

            String ID = IdAlbumCon.getText();

            String query = "SELECT * FROM album WHERE id like " + ID;
            Statement sta = gc.conn1.createStatement();

            ResultSet rs = sta.executeQuery(query);

            ResultSetMetaData metaDatos = rs.getMetaData();

            int numColumnas = metaDatos.getColumnCount();

            tablaModel = new DefaultTableModel();

            this.jTable1.setModel(tablaModel);

            for (int i = 1; i <= numColumnas; i++) {
                tablaModel.addColumn(metaDatos.getColumnLabel(i));
            }

            while (rs.next()) {
                Object[] fila = new Object[numColumnas];

                for (int i = 0; i < numColumnas; i++) {
                    fila[i] = rs.getObject(i + 1);
                }
                tablaModel.addRow(fila);
            }

            rs.close();

            sta.close();

            System.out.println("Consulta Correcta");

        } catch (Exception e) {
            e.printStackTrace();
            cadenaResult = e.toString();
            Error.setText(cadenaResult);
        }
    }//GEN-LAST:event_ConsultaAlbumMouseClicked

    private void TablaCancionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaCancionMouseClicked
        try {
            gc.conn1.setAutoCommit(false);

            String query = "SELECT * FROM cancion ";

            Statement sta = gc.conn1.createStatement();

            ResultSet rs = sta.executeQuery(query);
            ResultSetMetaData metaDatos = rs.getMetaData();

            int numColumnas = metaDatos.getColumnCount();

            tablaModel = new DefaultTableModel();

            this.jTable1.setModel(tablaModel);

            for (int i = 1; i <= numColumnas; i++) {
                tablaModel.addColumn(metaDatos.getColumnLabel(i));
            }

            while (rs.next()) {
                Object[] fila = new Object[numColumnas];

                for (int i = 0; i < numColumnas; i++) {
                    fila[i] = rs.getObject(i + 1);
                }
                tablaModel.addRow(fila);
            }

            rs.close();

            sta.close();

        } catch (Exception e) {
            e.printStackTrace();
            cadenaResult = e.toString();
            Error.setText(cadenaResult);
        }
    }//GEN-LAST:event_TablaCancionMouseClicked

    private void TablaAlbumMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaAlbumMouseClicked
        try {
            gc.conn1.setAutoCommit(false);

            String query = "SELECT * FROM album ";

            Statement sta = gc.conn1.createStatement();

            ResultSet rs = sta.executeQuery(query);
            ResultSetMetaData metaDatos = rs.getMetaData();

            int numColumnas = metaDatos.getColumnCount();

            tablaModel = new DefaultTableModel();

            this.jTable1.setModel(tablaModel);

            for (int i = 1; i <= numColumnas; i++) {
                tablaModel.addColumn(metaDatos.getColumnLabel(i));
            }

            while (rs.next()) {
                Object[] fila = new Object[numColumnas];

                for (int i = 0; i < numColumnas; i++) {
                    fila[i] = rs.getObject(i + 1);
                }
                tablaModel.addRow(fila);
            }

            rs.close();

            sta.close();

        } catch (Exception e) {
            e.printStackTrace();
            cadenaResult = e.toString();
            Error.setText(cadenaResult);
        }
    }//GEN-LAST:event_TablaAlbumMouseClicked

    private void InsertarCancionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InsertarCancionMouseClicked
        gc.insertarCancion(TituloCancion.getText(), DuracionCancion.getText(), LetrasCancion.getText(), AlbumCancion.getText());
        TablaCancionMouseClicked(evt);
        Error.setText(gc.cadenaResult);
    }//GEN-LAST:event_InsertarCancionMouseClicked

    private void CaratulaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CaratulaMouseClicked
        Caratula.setText("");
    }//GEN-LAST:event_CaratulaMouseClicked

    private void TituloCancionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TituloCancionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TituloCancionActionPerformed

    private void InsertCaratulaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InsertCaratulaMouseClicked
        gc.Anade(Caratula.getText());
        Error.setText(gc.cadenaResult);
    }//GEN-LAST:event_InsertCaratulaMouseClicked

    private void CaratulaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CaratulaMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_CaratulaMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AlbumCancion;
    private javax.swing.JTextField Caratula;
    private javax.swing.JButton ConsultaAlbum;
    private javax.swing.JTextField DuracionCancion;
    private javax.swing.JLabel Error;
    private javax.swing.JTextField Id;
    private javax.swing.JTextField IdAlbumCon;
    private javax.swing.JButton InsertCaratula;
    private javax.swing.JButton InsertarAlbum;
    private javax.swing.JButton InsertarCancion;
    private javax.swing.JTextField LetrasCancion;
    private javax.swing.JButton TablaAlbum;
    private javax.swing.JButton TablaCancion;
    private javax.swing.JTextField Titulo;
    private javax.swing.JTextField TituloCancion;
    private javax.swing.JTextField Year;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
